### ISSUE TITLE
"Data Management" name is too generic

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/dine-safe-ly#10]
The [Data Management](https://github.com/gcivil-nyu-org/dine-safe-ly/wiki/High-Level-Context-Diagram#data-management---admin) epic name is too generic and confusing.

**Comment by deusalexmachina** [comment]
We have edited the epic name for clarity, and also added some user stories under the description to help give a better sense of what the Epic entails.
