### ISSUE TITLE
As an admin, I want to search the database so that I may identify and extract meaningful data points.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#11]
**User story**
As an admin, I want to search the database so that I may identify and extract meaningful data points.

**Acceptance criteria**

- As an admin, I should be able to identify column data for business identification, location, and inspection details.
- As an admin, I should be able to parse through a processed database and extract relevant data points.

**Definition of Done**
- Meaningful data can be extracted from the database.

**Comment by vinayaknatarajan** [comment]
![UserQueryActivity](https://user-images.githubusercontent.com/45198069/94614202-cd12fb80-0273-11eb-981a-6d950bcda9d5.png)
