### ISSUE TITLE
possible UX issue 

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/dine-safe-ly#157]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Actually this seems like a UX Bug so I am explaining

The main page says "What are you searching for?" 
I type "japanese"
it assumes that this is a restaurant name?  Seems a bit weird.
 

## Expected Behavior

Given that the prompt is "What are you searching for?" I would expect search results

## Current Behavior

Assumes that the search is for the restaurant name, seems

## Ideas for Improvement

Either make it work ( hard-er) or change the prompt (easier) 
NOTE:
A similar project in this class prompts for the search "Restaurant Name, category, zip code, etc" - and this seems to mostly work

## Steps to Reproduce
See attached [Screen Recording 1.mov.zip](https://github.com/gcivil-nyu-org/dine-safe-ly/files/5592964/Screen.Recording.1.mov.zip) -- unzip first.

**Comment by ronakf11** [comment]
Thanks for reporting this to us.
We'll have a discussion and see how we want to proceed with this.
