### ISSUE TITLE
Password update button does not send any reset link and logged out user without prompt

### ISSUE THREAD

**Issue by sesha14** [gcivil-nyu-org/dine-safe-ly#159]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

There is no reset link sent as mentioned in the guide and no prompt to the user specifying what happened after clicking the update password button. The user just sees the button highlighted and might think it is not working.

## Expected Behavior
-The user should be sent a reset link (that is what is written in the guide so it is up to the team to have a reset link or not).
In my view, since the user is already able to provide a new password in the page reset link is not needed.
- The user should be given a prompt saying "password updated and you are logged out. Please sign in with the updated password"

## Current Behavior
I observed that on the password update page in the profile when we enter a new password and click the update password button, there is no reset link sent despite having a valid email account linked to the account. Also, the button just gets highlighted and does not leave any message as updated and if we refresh the page the user is simply logged out with the password updated automatically.

## Ideas for Improvement
Could simply redirect to forgot password functionality or simply update automatically without reset link and add a user prompt to login again.

## Steps to Reproduce
1.Redirect the button to the forgot password functionality already existing in the app.
2.Add a user prompt specifying what is happening.

## Context (Environment)
As a user, I could not understand if my password was updated or not and was waiting for reset link(as it was mentioned in the user guide)

**Comment by deusalexmachina** [comment]
Hi Sesha,

Password recovery (aka forgotten password) generates a reset link sent to your email. Updating a password does not require a reset link. These are two separate processes. But thank you for pointing out the update bug, since updating a password should auto-redirect to logout and prompt user to sign in again.

Alex
