### ISSUE TITLE
Scrolling error on main page

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/dine-safe-ly#160]
## Expected Behavior

When I scroll, I expect that the dots(scroller) follows my scroll

## Current Behavior

Even if I'm at the last restaurant of the list, the dot underneath show that I am in the middle.
![image](https://user-images.githubusercontent.com/60978943/100168157-b2818b00-2e8e-11eb-8353-a85bd9f37134.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thanks for reporting this to us.
We'll have a discussion and see how we want to proceed with this.
