### ISSUE TITLE
Save/remove button when not logged in

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/dine-safe-ly#161]
## Expected Behavior

If not logged in, I don't expect to see a "like" button,
or if I click on it, ask for registration.

## Current Behavior

The button is shown, and when clicked, nothing happens
![image](https://user-images.githubusercontent.com/60978943/100168431-43586680-2e8f-11eb-8eef-0ff9132346c3.png)

## Ideas for Improvement

have the button shown only when logged in

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thanks for reporting this to us.
We'll have a discussion and see how we want to proceed with this.
