### ISSUE TITLE
Inactive button on Information section

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/dine-safe-ly#162]
Clicked on icons in the information section.

## Expected Behavior

I expect them not to be clickable.

## Current Behavior

Below buttons are clickable, but do not link to any website, or initiate a behavior.
![image](https://user-images.githubusercontent.com/60978943/100168612-97fbe180-2e8f-11eb-90d6-5145a84a3082.png)

## Ideas for Improvement

Deactivate click on the buttons.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thanks for reporting this to us.
We'll have a discussion and see how we want to proceed with this.
