### ISSUE TITLE
Load more arrow button not showing on first click

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/dine-safe-ly#163]
## Expected Behavior

I expect that there will only be Load more button when I'm at the initial stage.
AND
expect to see back to top arrow button when I'm with more pages.

## Current Behavior

1. currently I see the arrow button at initial stage
   (I do think this can be preference, but to me it makes more sense not to have the button at this stage.
![image](https://user-images.githubusercontent.com/60978943/100168992-6afbfe80-2e90-11eb-85e9-ccad6d1f3807.png)

2. the real issue is when I click on Load More for the first time, when I scroll down, I do not see a back to top button.
![image](https://user-images.githubusercontent.com/60978943/100169153-c3330080-2e90-11eb-8eb2-2f6ffbb91bb8.png)
However, on the second, thrid click I see the button.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thanks for reporting this to us.
We'll have a discussion and see how we want to proceed with this.
