### ISSUE TITLE
Unable to view cuisine preferences in the user profile.

### ISSUE THREAD

**Issue by rossy312** [gcivil-nyu-org/dine-safe-ly#165]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.
 
Unable to view cuisine preferences in the user profile.

## Expected Behavior
I expected to be able to view the cuisine preferences I had selected and saved successfully.

## Current Behavior
When I clicked on Personal Preferences, I only saw the Category drop-down menu and the "Save Your Preferences" -- exactly the same thing I saw before saving my cuisine preferences initially.

## Ideas for Improvement
I would like to be able to see the cuisine preference I selected. What if I can't remember what I entered? 

## Steps to Reproduce
1. I clicked on Account Details.
2. I clicked on Personal Preferences.
3. I entered three different preferences and clicked "Save Your Preferences."
4. I then clicked on Personal Preferences again, and did not see any change indicating what my preferences were.

**Comment by ronakf11** [comment]
Thanks for reporting this to us.
We'll have a discussion and see how we want to proceed with this.
