### ISSUE TITLE
Log in with Goolge Error

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/dine-safe-ly#166]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Select log in with google will load Google Accounts log in page

## Current Behavior
Select log in with google, throws Error 400: redirect_uri_mismatch

## Steps to Reproduce

1. Log out of all Google Accounts and Facebook Accounts (to prevent conflicts according to the Testing Guide)
2. Navigate to Dine-safe.ly webpage
3. Click log in
4. Click log in with Google
5. Error 400: redirect_uri_mismatch
![image](https://user-images.githubusercontent.com/30580940/100180040-5b3ae500-2ea5-11eb-8545-e0683ad14506.png)

## Context (Environment)

As as user, I was trying to log in using my Google Account to make my login easier.
Environment: Chrome

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
Although we were not able to recreate the same issue on our side and it would be helpful if we can get some additional information.
