### ISSUE TITLE
Scroll to Top Button diappears

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/dine-safe-ly#167]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Scroll to Top Button should always appear in Search page after results are loaded for easy scroll up to top section

## Current Behavior
Scroll to Top Button disappears after clicking on Load More for the first time and then re-appears after click on Load More second time. 

## Steps to Reproduce

1. Search for 'chicken'
2. Load More and Scroll to Top is visible
3. Click on Load More 
4. Load More is visible, but Scroll to Top disappears
5. Click on Load More 
6. Load More and Scroll to Top is visible

## Context (Environment)

As a user I would like to always be able to scroll to the top from the bottom of the page provided that the functionality is there.
Environment: Chrome

**Comment by ronakf11** [comment]
Duplicate to issue #163
