### ISSUE TITLE
After submitting the experience once, every page reload increases/decreases the avg. rating based on the last review

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/dine-safe-ly#171]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

If I submit the experience form once for any restaurant, every page reload increases/decreases the avg. rating based on the last review

## Expected Behavior

The rating should not change on reload.

## Current Behavior

The avg rating increases/decreases based on the last review.

## Ideas for Improvement

I suppose it's submitting the form on every reload.

## Steps to Reproduce

1. Navigate to a restaurant page
2. Check the avg. rating. (Suppose it's none)

![image](https://user-images.githubusercontent.com/55005259/100264438-74c74580-2f14-11eb-9aa2-e58d79960bac.png)

3. Submit the experience form with a rating 3.

![image](https://user-images.githubusercontent.com/55005259/100264531-91fc1400-2f14-11eb-82de-18302f5e9e09.png)

4. Submit one more review with rating 4. So the avg goes to 3.5
![image](https://user-images.githubusercontent.com/55005259/100264751-e2737180-2f14-11eb-9b86-aa9b3d85d96b.png)

5. No reload the page with chome reload. (It will ask if you wanna submit the form again)
![image](https://user-images.githubusercontent.com/55005259/100264965-26ff0d00-2f15-11eb-8736-c7d4d35c5ab5.png)

6. if you say yes, the rating would be increased to 3.67

![image](https://user-images.githubusercontent.com/55005259/100265062-4c8c1680-2f15-11eb-98bc-815da7f9c686.png)

The next reload makes it 3.75. So if you keep reloading, it keeps increasing.

**Comment by Chuanqi927** [comment]
Hello, thanks for pointing this out. If you refresh the page, chrome will ask you do you like to submit the form again. If you click on yes, basically you will submit another form with exactly the same choice you made before. In this case, you are submitting a safety level rating as 4. So the average will increase. If you keep refreshing the page, you will be keep submitting the same form, which is done by chrome.

**Comment by gauravag2207** [comment]
HI @Edward0o0 ,

I understand that, but I assume that can be prevented. And thinking about the real-world scenarios, users can reload the page.

Thanks,
Gaurav

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue.
