### ISSUE TITLE
The reviews data is inconsistent across the page

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/dine-safe-ly#172]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The number of reviews and stars data is inconsistent across the restaurant page.

## Expected Behavior

The number of reviews and the stars should match everywhere on the page.

## Current Behavior

The number of reviews and the stars have 2 different values on 2 different places on the page.

## Steps to Reproduce

1. Go to the Jue Lan Club restaurants page.
2. Check the number of reviews.
![image](https://user-images.githubusercontent.com/55005259/100265801-6712bf80-2f16-11eb-9070-7aafa8e9e30e.png)
![image](https://user-images.githubusercontent.com/55005259/100265892-87427e80-2f16-11eb-93cd-a3ac893c8e0f.png)

**Comment by Chuanqi927** [comment]
Hello, thanks for pointing that out. To better explain this, The review number at the top is number of people who reviewed this restaurant provided by Yelp. The review star at the top is average rating for this restaurant provided by Yelp as well. The star as 3.5 in Information card is also the same rating. Average Safety Rating is an independent rating based on Safety and only based on users who are using our application. We will make this information more clear to user in the future.

**Comment by gauravag2207** [comment]
Hi @Edward0o0,
But the yelp stars are 4 and not 3.5.
Also, since you marked this duplicate, it would be great if you may point out the issue# of the duplicate.

Thanks

**Comment by Chuanqi927** [comment]
> Hi @Edward0o0,
> But the yelp stars are 4 and not 3.5.
> Also, since you marked this duplicate, it would be great if you may point out the issue# of the duplicate.
> 
> Thanks

The yelp star is actually 3.5, we displayed it as 4 stars in the padding because we rounded it to integer for better dispalying. We will make that consistent. This is duplicate to your issue #173

**Comment by gauravag2207** [comment]
Hi @Edward0o0 
#173 is about the reviews not being integer. But this is about data being inconsistent. I raised both of them and don't think they are duplicates.
Also, for duplicates, as per my understanding, only one of the 2 should be marked as a duplicate and one should be kept as original. 
Thanks

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue.
