### ISSUE TITLE
The number of issues are in decimal, like 1.5

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/dine-safe-ly#173]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The number of reviews is in decimal like 1.5 etc. Is this possible?

## Expected Behavior

The number of reviews should be an Integer I believe.

## Current Behavior

The number of reviews is in decimal like 1.5

## Steps to Reproduce

1. Go to TGI's friday restaurants detail page. (https://dine-safe-ly.herokuapp.com/restaurant/profile/4753/#)
2. Check the reviews under information. It's 1.5. This is not rating as well as the avg. rating is 5.
![image](https://user-images.githubusercontent.com/55005259/100266760-f5d40c00-2f17-11eb-9b99-fca358515ee2.png)

**Comment by gauravag2207** [comment]
Hi @Edward0o0 ,
It would be great if you can link the duplicate bug number.

Thanks,
Gaurav

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue number #172 .
