### ISSUE TITLE
Review Stars are not stacked together

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/dine-safe-ly#175]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
The Starts for Review should be stacked together

## Current Behavior
The Stars for Review are not stacked together

## Steps to Reproduce

1. Open Dine-safe.ly website
2. Search for TGI 
3. Open the First result
4. Review stars are not stacked together
![image](https://user-images.githubusercontent.com/30580940/100274145-efe82600-2f2b-11eb-88d7-71e9ce72ec13.png)

Another Example:
![image](https://user-images.githubusercontent.com/30580940/100274080-d3e48480-2f2b-11eb-95eb-1b10dea59f24.png)

## Context (Environment)

Contributes to UI/UX
Environment: Chrome

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue #155
