### ISSUE TITLE
Add warning for not logged in users when click on save/unsave button

### ISSUE THREAD

**Issue by Huanjin-Zhang** [gcivil-nyu-org/dine-safe-ly#176]
## Expected Behavior 
By following the test guide, I try to search and browse restaurants without login. There is one "heart" button on the restaurant profile page. After clicking on that button, it's better to send a warning to users so that they know what needs to do to use this feature. Sometimes users forget they are not logged in.

## Current Behavior
Without login, the button has no response when users click it.

## Ideas for Improvement
Add one warning message to inform users they are not logged in.

## Steps to Reproduce
1.
2.
3.
4.

**Comment by Chuanqi927** [comment]
Hello, thanks for pointing this out. Currently we did not allow not-logged-in user to click on that heart button. We can improve it to pop up a notification to have them knew that only logged in user are allowed to save/delete.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue #161
