### ISSUE TITLE
Restaurant profile 17 is missing

### ISSUE THREAD

**Issue by shivangpandya** [gcivil-nyu-org/dine-safe-ly#179]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

When I should go to the restaurant I should see the restaurant name along with it details

## Current Behavior

Restaurant 17 shows a blank output with no details

## Ideas for Improvement

Maybe some data cleaning from API or database

## Steps to Reproduce

1.Sign in as user
2.Go to https://dine-safe-ly.herokuapp.com/restaurant/profile/17/
3. 

<img width="1440" alt="Screen Shot 2020-11-25 at 6 00 34 PM" src="https://user-images.githubusercontent.com/13718156/100290034-5bd88780-2f48-11eb-96cc-c6d3e34d13ed.png">

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue #164
