### ISSUE TITLE
SUGGESTION: Add account created message on login screen after sign up

### ISSUE THREAD

**Issue by ponathanjun** [gcivil-nyu-org/dine-safe-ly#180]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After registering for an account, the website automatically redirects you to the login page without stating if your account was created or not.
## Expected Behavior

After creating an account, the website should automatically redirect you to the login page with an account creation status update.
## Current Behavior

After creating an account, the website redirects you to the login page with no status update on the creation of the account.
## Ideas for Improvement

If account creation was successful, send a message that states something along the lines of "Account created." to the login html page and from the login html page, write an if statement to see if a message is available and then print it.
## Steps to Reproduce

1. Sign up for an account (automatically redirects to login page)

## Context (Environment)

Without having a status update, I was just confused on what happened after registration. In reality, this has no affect on the product itself, but it's more of a quality of life suggestion.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this suggestion.
