### ISSUE TITLE
Account details favorite restaurants does not differentiate between restaurants with the same name

### ISSUE THREAD

**Issue by ponathanjun** [gcivil-nyu-org/dine-safe-ly#181]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

I should be able to differentiate between restaurants with the same name (chains usually) in the favorite restaurants section of the account detail page.
## Current Behavior

I see two restaurants with the same name and it's impossible to find out which restaurant each tag is referring to if I want to remove one from my favorites.
## Ideas for Improvement

Maybe link each tag with the restaurant page so we can differentiate or have some sort of distinguisher.
## Steps to Reproduce

1. Create an account.
2. Login
3. Search SWEETGREEN in restaurants and favorite multiple
4. Look at account details page and see many sweetgreen restaurants favorited but no way to differentiate between them

## Context (Environment)

If I had a bad experience with a restaurant and I have multiple of the same chain favorited, it's impossible to remove that specific restaurant from the account detail page (will have to search the specific restaurant to favorite/unfavorite).

**Comment by Chuanqi927** [comment]
Hello, thank you for pointing that out. You are right. Currently we only display the name of your favorite restaurant without hyperlinking it. We can do that for enhancement in the future.
