### ISSUE TITLE
On rating the safety level , it does not show average of reviews

### ISSUE THREAD

**Issue by shivangpandya** [gcivil-nyu-org/dine-safe-ly#182]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

On clicking the safety rating on the restaurant page, the  safety error check should  be an average of previous reviews and my review
## Current Behavior

On clicking the safety button without selecting any of the above checkmarks, it does not calculate the average score. However, when I select all the fields along with other radio buttons it calculates average
## Steps to Reproduce

1. Go to any restaurant page
2. Select the button ' have you ever been before'?
3. Just give ratings based on safety leaving everything else blank  
4. The average doesnt change

**Comment by Chuanqi927** [comment]
Hello, regarding this issue, the reason is that we made all the fields as requried before submission. If you do not select all the options, no submission will be made, so there will be no new average rating. We will enhance this to notify user to select all fields. Thank you

> Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.
> 
> ## Expected Behavior
> On clicking the safety rating on the restaurant page, the safety error check should be an average of previous reviews and my review
> 
> ## Current Behavior
> On clicking the safety button without selecting any of the above checkmarks, it does not calculate the average score. However, when I select all the fields along with other radio buttons it calculates average
> 
> ## Ideas for Improvement
> ## Steps to Reproduce
> 1. Go to any restaurant page
> 2. Select the button ' have you ever been before'?
> 3. Just give ratings based on safety leaving everything else blank
> 4. The average doesnt change
> 
> ## Context (Environment)

**Comment by Chuanqi927** [comment]
it is a duplicate issue as #177 and #170

**Comment by shivangpandya** [comment]
Ah... Thanks for notifying me. I didn't notice this issue had been raised.
