### ISSUE TITLE
Chatbot says something went wrong. I tend to agree

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/dine-safe-ly#184]
See my chatbot interaction below

Hi prof_test, I'm your Personal Concierge. How can I help?

19:37

restaurant in chelsea

19:37

user
user
Got it. What cuisine would you like to try?

19:37

Japanese

19:37

user
user
What's the keyword in restaurant name?

19:37

Tokyo

19:37

user
user
What's the keyword in restaurant name?

19:37

Sushi

19:37

user
user
Oops, something went wrong. Please try again.

19:37

**Comment by Chuanqi927** [comment]
Hello professor, thanks for pointing that out. Chatbot is a feature we were doing this week and we did not have enough time to fully implement it to our expectation. So we mentioned in the test gudie to Not Test.

**Comment by gcivil-nyu** [comment]
Ah, my bad I did not notice that. Feel free to close
