### ISSUE TITLE
Search by Restaurant Name doesn't work for all Restaurants

### ISSUE THREAD

**Issue by gsavitha** [gcivil-nyu-org/dine-safe-ly#185]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Search for certain restaurants by name returns no result, even when restauarant is displayed in unfiltered search.

## Expected Behavior
Searching for exisiting restaurants displayed should return results.

## Current Behavior
Incomplete / No Results returned. 
## Steps to Reproduce
1. Navigate to restaurants page.
2. Restaurant "Emily" is present here. 
![image](https://user-images.githubusercontent.com/17599828/100294706-9563bf80-2f55-11eb-873c-30e0f2f306f5.png)

3. Seach for "Emily"
4. No Results returned
![image](https://user-images.githubusercontent.com/17599828/100294835-f2f80c00-2f55-11eb-8af1-9e4de8576bca.png)

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue.
