### ISSUE TITLE
Name changed to lowercase when logging in with facebook

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/dine-safe-ly#186]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

![image](https://user-images.githubusercontent.com/3640558/100295743-55eaa280-2f58-11eb-9061-6067e50a1135.png)

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
