### ISSUE TITLE
Suggestion: In chatbot, maybe have a more generic profile user logo as the default user picture

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/dine-safe-ly#187]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.
![image](https://user-images.githubusercontent.com/3640558/100295778-7dda0600-2f58-11eb-83be-ab730868f0a5.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thank you for this suggestion.
