### ISSUE TITLE
UI enhancement suggestion: Chatbot result return

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/dine-safe-ly#188]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.
The returned chatbot result would be better if it's a clickable short link instead of the non-clickable url
![image](https://user-images.githubusercontent.com/3640558/100295869-c7c2ec00-2f58-11eb-9212-98b74bc10b4b.png)

By the way, good job inplementing it :D

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
This was not part of our testable features so what you reported is still under development.
Thank You.
