### ISSUE TITLE
Test restaurant profile still available for access

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/dine-safe-ly#189]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.
https://dine-safe-ly.herokuapp.com/restaurant/profile/3/
I assume this is a test restaurant page and I think you might want to take it off :)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue in reference to issue #164
