### ISSUE TITLE
Suggestion: Set Debug mode as off for production site

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/dine-safe-ly#190]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.
![image](https://user-images.githubusercontent.com/3640558/100296143-736c3c00-2f59-11eb-837a-26a7090ec742.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
