### ISSUE TITLE
UI suggestion: tag should not show up as a link if they aren't clickable

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/dine-safe-ly#192]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

In addition, the "Breakfast_branch" should parse the underscore to space
![image](https://user-images.githubusercontent.com/3640558/100296544-89c6c780-2f5a-11eb-8e14-33030afd7f90.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue.
