### ISSUE TITLE
use percentage instead of T/F for user feedback

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/dine-safe-ly#194]
it can come too arbitrary to use the latest feedback to decide if a location is doing a certain preventative action.

consider something like:
- "88% of customers reported this bistro is taking temperature check" 
- or even trends like "according to user feedback, this location started to and now take temperature check"

and even allowing user to post feedback in brief texts, or choosing among pre-defined tags.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue.
