### ISSUE TITLE
Some restaurants are not able to Favorite

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/dine-safe-ly#196]
some restaurants in the list links to `profile/` while others link to `inspection_records`. The latter group will not be able to be marked as favorite. and this seems random.

Compare the link revealed in the lower left corner of the two screenshots:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/24606632/100299044-b1209300-2f60-11eb-8286-a9602a6daf3e.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/24606632/100299053-b4b41a00-2f60-11eb-986d-b1d659dbc0c7.png">

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue.
