### ISSUE TITLE
Not able to understand which value the user is missing while signing up

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/dine-safe-ly#197]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

While signing up, I was not able to pass the validations but I wasn't able to figure out which field's validation I actually failed. 

## Expected Behavior

I think the error should specify exactly which field's validation is not proper.

## Current Behavior

<img width="1440" alt="Screen Shot 2020-11-25 at 8 53 25 PM" src="https://user-images.githubusercontent.com/29802097/100299071-c0074580-2f60-11eb-9392-fa70cb63cc76.png">

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue .
