### ISSUE TITLE
BUG: Able to create account completely with numbers

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/dine-safe-ly#198]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Able to create an account by entering only numbers for Username
## Expected Behavior

Should not be able to create an account if the user enters only numbers

## Current Behavior

I can create an account by entering only the numbers

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue.
