### ISSUE TITLE
Email verification not present but forgot password present 

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/dine-safe-ly#199]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Let's say you create an account with email-abc@abc.com, username-56789 and since your website doesn't verify accounts, I can login into the website immediately. Now, when I come to reset my password, I won't be able to do that since that account is never verified because the email entered is not a legitimate one and that completely the defeats the purpose of "Forgot Password". I think verifying accounts with appropriate emails should be important to make "Forgot Password" feature a complete success.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ronakf11** [comment]
Thank you for reporting this to us.
We are currently looking into this issue .
