### ISSUE TITLE
As a user, I want to view a "browse" page so that I may view restaurants by compliance status and other search filters.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#21]
**User story**

- As a user, I want to view a "browse" page so that I may view restaurants by compliance status and other search filters.

**Acceptance criteria**

- Given that I am a user, I should be able to browse for restaurants on a landing page.

**Definition of Done**

- [ ] Present list of restaurants by card, with **clear** visual indication regarding compliance (ordered by most recent / compliant-only).

**Comment by Chuanqi927** [comment]
This user story is about getting the results based on text input query. The results are displayed in text format and based on NYC Open data.

**Comment by Chuanqi927** [comment]
The search results are based on the information we retrieve from Yelp
