### ISSUE TITLE
As a user, I want to provide feedback on my overall experience so that I may help other users make decisions.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#22]
**User story**

- As a user, I want to provide feedback on my experience so that I may help other users make decisions.

**Acceptance criteria**

- Given that I am a user, I have the option to answer basic questions related to the restaurant's implementation of COVID safety features. (6 feet distance between tables, adequate ventilation, temperature checks, etc).

**Definition of Done**

- Users can submit yes/no questions pertaining to COVID restaurant guidelines.

**Comment by vinayaknatarajan** [comment]
Tasks
- create a business survey model to store user scores for each restaurant.
- add a link to the complaint form.
- Add popup box for the user survey
