### ISSUE TITLE
As a user, I want to view a restaurant's inspection history so that I can see if a business has regularly maintained compliance.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#27]
**User story**

- As a user, I want to view a restaurant's inspection history so that I can see if a business has regularly maintained compliance.

**Acceptance criteria**

- A user can open a restaurant's inspection page and see an updated list of inspection history.

**Definition of Done**

- [ ] Each restaurant page will have an accessible link to its historical inspection data.
- [ ] Code is reviewed and tested.

**Comment by deusalexmachina** [comment]
Docs
- [ ] API Documentation

Backend
- [ ] Create DB Model for Restaurants (ID, Name, Address/Zip Code)
- [ ] Create DB Model for Inspection Data
- [ ] Socrata API calls for initial data set processing

Data
- [ ] Pre-process data
- [ ] Business matching (open data <-> Yelp)
- [ ] Populate database(s)

Front End
- [ ] Create basic front end for restaurant page
- [ ] Create basic front end for restaurant inspection history

Testing
- [ ] Verify correct values in db
- [ ] Verify API matching

**Comment by Chuanqi927** [comment]
Work Divided: Chenwei and Alex will be doing DB model and populate databases. Vinayak will be socrata API calls for inspection data and pre-process data, I will be doing Business matching between inspection data and yelp data. Ronak will be doing Front end

**Comment by deusalexmachina** [comment]
Separate page, make more pronounced.
