### ISSUE TITLE
As a user, I want to view a restaurant's address, operational hours, and other pertinent info such as reviews and services.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#28]
**User story**

- As a user, I want to view a restaurant's address, operational hours, and other pertinent info such as reviews and services.

**Acceptance criteria**

- Given that I am a user, I can open a restaurant's page and view information such as average user reviews, hours of operation, and helpful info provided by Yelp.

**Definition of Done**

- A user can open a page and see basic restaurant information on the landing page.

**Comment by Chuanqi927** [comment]
The information is based on Yelp
