### ISSUE TITLE
As a user, I want to be able to search restaurants by name, and other attributes.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#57]
Backend:
- Search based on restaurant name keyword
- Search based on restaurant location (zipcode)

Maybe just integrate this for filter:
- Search based on restaurant categories

Frontend:
- Reformat browse page

Definition of done:
- Browse page should display the correct results of search and filter;
- We should be able to apply filter to the search results;

**Comment by Chuanqi927** [comment]
Home page search implementation
