### ISSUE TITLE
As a user, I want to filter restaurants by attributes so that I can access restaurants by category on a browse page.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#58]
**User story**
- As a user, I want to filter restaurants by attributes so that I can access restaurants by category on a browse page
**Acceptance criteria**
Filter by:
- Category
- Ratings
- Price $$$
- neighborhood 

**Definition of Done**
- Getting filtered restaurants based on filter attributes.
- Filter feature should work with search feature

**Comment by vinayaknatarajan** [comment]
Filters to be implemented:
- neighbourhood (mapped to zipcode)
- compliance

Future scope
- rating
- cuisine/category
- price

**Comment by Chuanqi927** [comment]
fix ratings filter
