### ISSUE TITLE
As a user, I want to be able to learn what it means to be compliant so that I may understand inspection results.

### ISSUE THREAD

**Issue by deusalexmachina** [gcivil-nyu-org/dine-safe-ly#66]
**User story**

**Acceptance criteria**

**Definition of Done**

**Comment by Chuanqi927** [comment]
Users can have like and dislike the questionnaire results

**Comment by Chuanqi927** [comment]
Only users can see the questionnaire button

**Comment by Chuanqi927** [comment]
Replace see all reviews on yelp instead of leave a review
